#!/bin/bash
export PATH=/usr/local/bin/:/usr/bin:/bin:$PATH
CUR_PATH=`pwd`
basepath=$(cd `dirname $0`; pwd)
echo $CUR_PATH
echo $basepath
cd $basepath
if [[ $1 = 'open' ]]; then
    python3 createECS.py
elif [[ $1 = 'close' ]]; then
    python3 DeleteECS.py
else
    python3 ECSInfo.py
fi

