#!/bin/bash
export PATH=/usr/local/bin/:/usr/bin:/bin:$PATH
CUR_PATH=`pwd`
basepath=$(cd `dirname $0`; pwd)
echo $CUR_PATH
echo $basepath
LOG=`nohup python pyfree.py &> /dev/null & echo $!`
# LOG=`nohup python klinetool.py > log.txt 2>&1 & echo $!`
# # LOG="12345"
echo $LOG
OUTSTR=$DATE"\n"$LOG
echo $OUTSTR > ssserverid.txt
echo 'pyfree start'