#!/bin/bash
export PATH=/usr/local/bin/:/usr/bin:/bin:$PATH
CUR_PATH=`pwd`
basepath=$(cd `dirname $0`; pwd)
echo $CUR_PATH
echo $basepath
if [[ $4 ]]; then
    nohup $1 $2 $3 $4 &> /dev/null &
elif [[ $3 ]]; then
    nohup $1 $2 $3 &> /dev/null &
elif [[ $2 ]]; then
    nohup $1 $2 &> /dev/null &
elif [[ $1 ]]; then
    nohup $1 &> /dev/null &
else
    echo "more perdata"
fi